slogan: "己所不欲，勿施于人。"

theme: cerulean
inverse: inverse

menu:
  - title: Archives
    url: archives
    intro: "All the articles"
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories"
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags"
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About Shuanglong"
    icon: "fa fa-user"

links:
  - title: Freemind
    url: https://github.com/wzpan/freemind/
    intro: "Freemind's Github repository"
    icon: "fa fa-github"
  - title: "Shuanglong Github"
    url: http://www.github.com/xautshuanglong
    intro: "My Github account"
    icon: "fa fa-github"
  - title: "Twitter"
    url: https://twitter.com/xautshuanglong
    intro: "My Twitter account"
    icon: "fa fa-twitter"
  - title: "Facebook"
    url: https://www.facebook.com/shuanglong.jiang
    intro: "My Facebook account"
    icon: "fa fa-facebook"

widgets:
- search
- category
- tagcloud
- recent_posts
- links
- weibo

rss: /atom.xml
fancybox: true
favicon: css/images/favicon.ico
#duoshuo_shortname: xautshuanglong

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: true
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false
