# Header
menu:
  Home: /
  Archives: /archives
  Rss: /atom.xml
  Sitemap: /sitemap.xml

# Content
excerpt_link: More
prev: Prev
next: Next
reply: Reply
share: Share
fancybox: true

# Sidebar
widgets:
- search
- recent_posts
- category
- tag
- tagcloud
- music
- weibo

# Miscellaneous
google_analytics:
duoshuo_shortname: 
rss:
google_site_verification: 
baidu_site_verification: 
favicon: 
music:
- take_you_fly.mp3
- dun_pai_qing_chun.mp3
